import atom.core;
#include "range/range_req_checks.h"

using namespace atom;

atom_satisfies_range_temp(range_req_mock);
atom_satisfies_mut_range_temp(mut_range_req_mock);
atom_satisfies_fwd_range_temp(fwd_range_req_mock);
atom_satisfies_mut_fwd_range_temp(mut_fwd_range_req_mock);
atom_satisfies_bidi_range_temp(bidi_range_req_mock);
atom_satisfies_mut_bidi_range_temp(mut_bidi_range_req_mock);
atom_satisfies_jump_range_temp(jump_range_req_mock);
atom_satisfies_mut_jump_range_temp(mut_jump_range_req_mock);
atom_satisfies_arr_range_temp(array_range_req_mock);
atom_satisfies_mut_arr_range_temp(mut_array_range_req_mock);
atom_satisfies_common_range_temp(common_range_req_mock);
atom_satisfies_mut_common_range_temp(mut_common_range_req_mock);
