#pragma once
#include "IterReq.h"

#define ATOM_STATIC_ASSERT_REQ_TEMP_ITER(TIterTemp);
#define ATOM_STATIC_ASSERT_REQ_TEMP_MUT_ITER(TIterTemp);
#define ATOM_STATIC_ASSERT_REQ_TEMP_ITER_OF(TIterTemp, T);
#define ATOM_STATIC_ASSERT_REQ_TEMP_MUT_ITER_OF(TIterTemp, T);

#define ATOM_STATIC_ASSERT_REQ_ITER(TIter);
#define ATOM_STATIC_ASSERT_REQ_ITER_OF(TIter, T);
#define ATOM_STATIC_ASSERT_REQ_MUT_ITER(TIter);
#define ATOM_STATIC_ASSERT_REQ_MUT_ITER_OF(TIter, T);

#define ATOM_STATIC_ASSERT_REQ_ITER_PAIR(TIter, TIterEnd);
#define ATOM_STATIC_ASSERT_REQ_ITER_PAIR_OF(TIter, TIterEnd, T);
#define ATOM_STATIC_ASSERT_REQ_MUT_ITER_PAIR(TIter, TIterEnd);
#define ATOM_STATIC_ASSERT_REQ_MUT_ITER_PAIR_OF(TIter, TIterEnd, T);